[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['cd backend && npm run build || true']

[start]
cmd = 'cd backend && npm start'

